import type { RequestHandler } from '@builder.io/qwik-city';

const data = {
  title: {
    unicode: 'ਕਬਯੋ ਬਾਚ ਬੇਨਤੀ - ਚੌਪਈ',
    roman: 'Kabyo Bāc Bentī Cōpaī',
  },
  paging: {
    previous: 'twa-prasad-swaye',
    next: 'anand-sahib',
  },
  data: [
    {
      id: 'WJ68',
      src: 'ੴ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਹ ॥',
      pronunciation: 'ik oañkār vāhigurū jī kī phatah ‖',
      translation: 'The Lord is One and the Victory is of the True Guru.',
    },
    {
      id: 'CHL7',
      src: 'ਪਾਤਿਸਾਹੀ ੧੦ ॥',
      pronunciation: 'pātisāhī 10 ‖',
      translation: '(By) Tenth Master, (in) Deviant Metre,',
    },
    {
      id: '6KNN',
      src: 'ਕਬਿਯੋ ਬਾਚ ਬੇਨਤੀ ॥ ਚੌਪਈ ॥',
      pronunciation: 'kabiyo bāc benatī ‖ cōpaī ‖',
      translation: 'Speech of the poet. Chaupai',
    },
    {
      id: 'R6ML',
      src: 'ਹਮਰੀ ਕਰੋ ਹਾਥ ਦੈ ਰੱਛਾ ॥',
      pronunciation: 'hamarī karo hāth dē racchā ‖',
      translation: 'Protect me O Lord! with Thine own Hands',
    },
    {
      id: 'P1M6',
      src: 'ਪੂਰਨ ਹੋਇ ਚਿਤ ਕੀ ਇੱਛਾ ॥',
      pronunciation: 'pūran hoi cit kī icchā ‖',
      translation: 'all the desires of my heart be fulfilled.',
    },
    {
      id: 'CP5D',
      src: 'ਤਵ ਚਰਨਨ ਮਨ ਰਹੈ ਹਮਾਰਾ ॥',
      pronunciation: 'tav caranan man rahē hamārā ‖',
      translation: 'Let my mind rest under Thy Feet',
    },
    {
      id: 'U8NW',
      src: 'ਅਪਨਾ ਜਾਨ ਕਰੋ ਪ੍ਰਤਿਪਾਰਾ ॥੩੭੭॥',
      pronunciation: 'apanā jān karo pratipārā ‖377‖',
      translation: 'Sustain me, considering me Thine own.377.',
    },
    {
      id: 'QXDA',
      src: 'ਹਮਰੇ ਦੁਸਟ ਸਭੈ ਤੁਮ ਘਾਵਹੁ ॥',
      pronunciation: 'hamare dusaṭ sabhē tum ghāwah ‖',
      translation: 'Destroy, O Lord! all my enemies and',
    },
    {
      id: 'SQJB',
      src: 'ਆਪੁ ਹਾਥ ਦੈ ਮੋਹਿ ਬਚਾਵਹੁ ॥',
      pronunciation: 'āp hāth dē moh bacāwah ‖',
      translation: 'protect me with Thine won Hnads.',
    },
    {
      id: 'AE2T',
      src: 'ਸੁਖੀ ਬਸੈ ਮੋਰੋ ਪਰਿਵਾਰਾ ॥',
      pronunciation: 'sukhī basē moro parivārā ‖',
      translation: 'May my family live in comfort',
    },
    {
      id: 'XFP4',
      src: 'ਸੇਵਕ ਸਿੱਖ ਸਭੈ ਕਰਤਾਰਾ ॥੩੭੮॥',
      pronunciation: 'sewak sikkh sabhē karatārā ‖378‖',
      translation: 'and ease alongwith all my servants and disciples.378.',
    },
    {
      id: 'R1TY',
      src: 'ਮੋ ਰੱਛਾ ਨਿਜ ਕਰ ਦੈ ਕਰਿਯੈ ॥',
      pronunciation: 'mo racchā nij kar dē kariyē ‖',
      translation: 'Protect me O Lord! with Thine own Hands',
    },
    {
      id: 'D8U7',
      src: 'ਸਭ ਬੈਰਨ ਕੋ ਆਜ ਸੰਘਰਿਯੈ ॥',
      pronunciation: 'sabh bēran ko āj sañghariyē ‖',
      translation: 'and destroy this day all my enemies',
    },
    {
      id: 'BG7D',
      src: 'ਪੂਰਨ ਹੋਇ ਹਮਾਰੀ ਆਸਾ ॥',
      pronunciation: 'pūran hoi hamārī āsā ‖',
      translation: 'May all the aspirations be fulfilled',
    },
    {
      id: 'V73H',
      src: 'ਤੋਰ ਭਜਨ ਕੀ ਰਹੈ ਪਿਆਸਾ ॥੩੭੯॥',
      pronunciation: 'tor bhajan kī rahē piāsā ‖379‖',
      translation: 'Let my thirst for Thy Name remain afresh.379.',
    },
    {
      id: 'B4AY',
      src: 'ਤੁਮਹਿ ਛਾਡਿ, ਕੋਈ ਅਵਰ ਨ ਧਿਯਾਊਂ ॥',
      pronunciation: 'tumah chāḍi, koī awar na dhiyāūñ ‖',
      translation: 'I may remember none else except Thee',
    },
    {
      id: 'KSTH',
      src: 'ਜੋ ਬਰ ਚਹੋਂ, ਸੁ ਤੁਮ ਤੇ ਪਾਊਂ ॥',
      pronunciation: 'jo bar cahoñ, sa tum te pāūñ ‖',
      translation: 'And obtain all the required boons from Thee',
    },
    {
      id: 'FHPG',
      src: 'ਸੇਵਕ ਸਿੱਖ ਹਮਾਰੇ ਤਾਰੀਅਹਿ ॥',
      pronunciation: 'sewak sikkh hamāre tārīah ‖',
      translation: 'Let my servants and disciples cross the world-ocean',
    },
    {
      id: '2JMJ',
      src: 'ਚੁਨਿ ਚੁਨਿ ਸਤ੍ਰ ਹਮਾਰੇ ਮਾਰੀਅਹਿ ॥੩੮੦॥',
      pronunciation: 'cun cun satr hamāre mārīah ‖380‖',
      translation: 'All my enemies be singled out and killed.380.',
    },
    {
      id: '6EUL',
      src: 'ਆਪ ਹਾਥ ਦੈ ਮੁਝੈ ਉਬਰਿਯੈ ॥',
      pronunciation: 'āp hāth dē mujhē ubariyē ‖',
      translation: 'Protect me O Lord! with Thine own Hands and',
    },
    {
      id: '4MS3',
      src: 'ਮਰਨ ਕਾਲ ਕਾ ਤ੍ਰਾਸ ਨਿਵਰਿਯੈ ॥',
      pronunciation: 'maran kāl kā trās niwariyē ‖',
      translation: 'relieve me form the fear of death',
    },
    {
      id: 'SLHB',
      src: 'ਹੂਜੋ ਸਦਾ ਹਮਾਰੇ ਪੱਛਾ ॥',
      pronunciation: 'hūjo sadā hamāre pacchā ‖',
      translation: 'May Thou ever Bestow Thy favours on my side',
    },
    {
      id: '5R1H',
      src: 'ਸ੍ਰੀ ਅਸਿਧੁਜ ਜੂ, ਕਰਿਯਹੁ ਰੱਛਾ ॥੩੮੧॥',
      pronunciation: 'srī asidhuj jū, kariyah racchā ‖381‖',
      translation: 'Protect me O Lord! Thou, the Supreme Destroyer.381.',
    },
    {
      id: '3DD4',
      src: 'ਰਾਖਿ ਲੇਹੁ ਮੁਹਿ ਰਾਖਨਹਾਰੇ ॥',
      pronunciation: 'rākh leh muh rākhanahāre ‖',
      translation: 'Protect me, O Protector Lord!',
    },
    {
      id: 'VD48',
      src: 'ਸਾਹਿਬ ਸੰਤ ਸਹਾਇ ਪਿਯਾਰੇ ॥',
      pronunciation: 'sāhib sañt sahāi piyāre ‖',
      translation: 'Most dear, the Protector of the Saints:',
    },
    {
      id: 'XGA3',
      src: 'ਦੀਨ ਬੰਧੁ ਦੁਸਟਨ ਕੇ ਹੰਤਾ ॥',
      pronunciation: 'dīn bañdh dusaṭan ke hañtā ‖',
      translation: 'Friend of poor and the Destroyer of the enemies',
    },
    {
      id: 'P2PS',
      src: 'ਤੁਮ ਹੋ, ਪੁਰੀ ਚਤੁਰਦਸ ਕੰਤਾ ॥੩੮੨॥',
      pronunciation: 'tum ho, purī caturadas kañtā ‖382‖',
      translation: 'Thou art the Master of the fourteen worlds.382.',
    },
    {
      id: 'K6XR',
      src: 'ਕਾਲ ਪਾਇ, ਬ੍ਰਹਮਾ ਬਪੁ ਧਰਾ ॥',
      pronunciation: 'kāl pāi, brahamā bap dharā ‖',
      translation: 'In due time Brahma appeared in physical form',
    },
    {
      id: 'URR4',
      src: 'ਕਾਲ ਪਾਇ, ਸਿਵ ਜੂ ਅਵਤਰਾ ॥',
      pronunciation: 'kāl pāi, siv jū awatarā ‖',
      translation: 'In due time Shiva incarnated',
    },
    {
      id: 'NQX3',
      src: 'ਕਾਲ ਪਾਇ ਕਰ, ਬਿਸਨੁ ਪ੍ਰਕਾਸਾ ॥',
      pronunciation: 'kāl pāi kar, bisan prakāsā ‖',
      translation: 'In due time Vishnu manifested himself',
    },
    {
      id: '7VQC',
      src: 'ਸਕਲ ਕਾਲ ਕਾ ਕੀਆ ਤਮਾਸਾ ॥੩੮੩॥',
      pronunciation: 'sakal kāl kā kīā tamāsā ‖383‖',
      translation: 'All this is the play of the Temporal Lord.383.',
    },
    {
      id: 'A9HF',
      src: 'ਜਵਨ ਕਾਲ, ਜੋਗੀ ਸਿਵ ਕੀਓ ॥',
      pronunciation: 'jawan kāl, jogī siv kīo ‖',
      translation: 'The Temporal Lord, who created Shiva, the Yogi',
    },
    {
      id: '48SM',
      src: 'ਬੇਦ ਰਾਜ, ਬ੍ਰਹਮਾ ਜੂ ਥੀਓ ॥',
      pronunciation: 'bed rāj, brahamā jū thīo ‖',
      translation: 'Who created Brahma, the Master of the Vedas',
    },
    {
      id: 'Z5CD',
      src: 'ਜਵਨ ਕਾਲ, ਸਭ ਲੋਕ ਸਵਾਰਾ ॥',
      pronunciation: 'jawan kāl, sabh lok savārā ‖',
      translation: 'The Temporal Lord who fashioned the entire world',
    },
    {
      id: '7SLL',
      src: 'ਨਮਸਕਾਰ ਹੈ, ਤਾਹਿ ਹਮਾਰਾ ॥੩੮੪॥',
      pronunciation: 'namasakār hē, tāh hamārā ‖384‖',
      translation: 'I salute the same Lord.384.',
    },
    {
      id: '2EJU',
      src: 'ਜਵਨ ਕਾਲ, ਸਭ ਜਗਤ ਬਨਾਯੋ ॥',
      pronunciation: 'jawan kāl, sabh jagat banāyo ‖',
      translation: 'The Temporal Lord, who created the whole world',
    },
    {
      id: '5LAZ',
      src: 'ਦੇਵ ਦੈਤ ਜੱਛਨ ਉਪਜਾਯੋ ॥',
      pronunciation: 'dev dēt jacchan upajāyo ‖',
      translation: 'Who created gods, demons and yakshas',
    },
    {
      id: 'WWUW',
      src: 'ਆਦਿ ਅੰਤਿ, ਏਕੈ ਅਵਤਾਰਾ ॥',
      pronunciation: 'ād añti, ekē awatārā ‖',
      translation: 'He is the only one form the beginning to the end',
    },
    {
      id: 'MKY4',
      src: 'ਸੋਈ, ਗੁਰੂ ਸਮਝਿਯਹੁ ਹਮਾਰਾ ॥੩੮੫॥',
      pronunciation: 'soī, gurū samajhiyah hamārā ‖385‖',
      translation: 'I consider Him only my Guru.385.',
    },
    {
      id: 'TK9G',
      src: 'ਨਮਸਕਾਰ, ਤਿਸ ਹੀ ਕੋ ਹਮਾਰੀ ॥',
      pronunciation: 'namasakār, tis hī ko hamārī ‖',
      translation: 'I salute Him, non else, but Him',
    },
    {
      id: '6C2M',
      src: 'ਸਕਲ ਪ੍ਰਜਾ ਜਿਨ ਆਪ ਸਵਾਰੀ ॥',
      pronunciation: 'sakal prajā jin āp savārī ‖',
      translation: 'Who has created Himself and His subject',
    },
    {
      id: 'HYGL',
      src: 'ਸਿਵਕਨ ਕੋ, ਸਿਵਗੁਨ ਸੁਖ ਦੀਓ ॥',
      pronunciation: 'siwakan ko, siwagun sukh dīo ‖',
      translation: 'He bestows Divine virtues and happiness on His servants',
    },
    {
      id: '5JSD',
      src: 'ਸੱਤ੍ਰੁਨ ਕੋ, ਪਲ ਮੋ ਬਧ ਕੀਓ ॥੩੮੬॥',
      pronunciation: 'sattrun ko, pal mo badh kīo ‖386‖',
      translation: 'He destroys the enemies instantly.386.',
    },
    {
      id: 'KTBW',
      src: 'ਘਟ ਘਟ ਕੇ ਅੰਤਰ ਕੀ ਜਾਨਤ ॥',
      pronunciation: 'ghaṭ ghaṭ ke añtar kī jānat ‖',
      translation: 'He knows the inner feelings of every heart',
    },
    {
      id: 'C4JM',
      src: 'ਭਲੇ ਬੁਰੇ ਕੀ ਪੀਰ ਪਛਾਨਤ ॥',
      pronunciation: 'bhale bure kī pīr pachānat ‖',
      translation: 'He knows the anguish of both good and bad',
    },
    {
      id: 'ZTEV',
      src: 'ਚੀਟੀ ਤੇ ਕੁੰਚਰ ਅਸਥੂਲਾ ॥',
      pronunciation: 'cīṭī te kuñcar asathūlā ‖',
      translation: 'From the ant to the solid elephant',
    },
    {
      id: 'KEE1',
      src: 'ਸਭ ਪਰ, ਕ੍ਰਿਪਾ ਦ੍ਰਿਸਟਿ ਕਰਿ ਫੂਲਾ ॥੩੮੭॥',
      pronunciation: 'sabh par, kripā drisaṭ kar phūlā ‖387‖',
      translation: 'He casts His Graceful glance on all and feels pleased.387.',
    },
    {
      id: '65FT',
      src: 'ਸੰਤਨ ਦੁਖ ਪਾਏ ਤੇ ਦੁਖੀ ॥',
      pronunciation: 'sañtan dukh pāe te dukhī ‖',
      translation: 'He is painful, when He sees His saints in grief',
    },
    {
      id: 'P8Z5',
      src: 'ਸੁਖ ਪਾਏ ਸਾਧੁਨ ਕੇ ਸੁਖੀ ॥',
      pronunciation: 'sukh pāe sādhun ke sukhī ‖',
      translation: 'He is happy, when His saints are happy.',
    },
    {
      id: 'L78Q',
      src: 'ਏਕ ਏਕ ਕੀ ਪੀਰ ਪਛਾਨੈਂ ॥',
      pronunciation: 'ek ek kī pīr pachānēñ ‖',
      translation: 'He knows the agony of everyone',
    },
    {
      id: 'DR9Y',
      src: 'ਘਟ ਘਟ ਕੇ, ਪਟ ਪਟ ਕੀ ਜਾਨੈਂ ॥੩੮੮॥',
      pronunciation: 'ghaṭ ghaṭ ke, paṭ paṭ kī jānēñ ‖388‖',
      translation: 'He knows the innermost secrets of every heart.388.',
    },
    {
      id: 'U9PE',
      src: 'ਜਬ, ਉਦਕਰਖ ਕਰਾ ਕਰਤਾਰਾ ॥',
      pronunciation: 'jab, udakarakh karā karatārā ‖',
      translation: 'When the Creator projected Himself,',
    },
    {
      id: 'KZHP',
      src: 'ਪ੍ਰਜਾ ਧਰਤ, ਤਬ ਦੇਹ ਅਪਾਰਾ ॥',
      pronunciation: 'prajā dharat, tab deh apārā ‖',
      translation: 'His creation manifested itself in innumerable forms',
    },
    {
      id: '42J2',
      src: 'ਜਬ, ਆਕਰਖ ਕਰਤ ਹੋ ਕਬਹੂੰ ॥',
      pronunciation: 'jab, ākarakh karat ho kabahūñ ‖',
      translation: 'When at any time He withdraws His creation,',
    },
    {
      id: 'L0YQ',
      src: 'ਤੁਮ ਮੈ ਮਿਲਤ, ਦੇਹ ਧਰ ਸਭਹੂੰ ॥੩੮੯॥',
      pronunciation: 'tum mē milat, deh dhar sabhahūñ ‖389‖',
      translation: 'all the physical forms are merged in Him.389.',
    },
    {
      id: 'BXD5',
      src: 'ਜੇਤੇ ਬਦਨ ਸ੍ਰਿਸਟਿ ਸਭ ਧਾਰੈ ॥',
      pronunciation: 'jete badan srisaṭ sabh dhārē ‖',
      translation: 'All the bodies of living beings created in the world',
    },
    {
      id: 'VWNC',
      src: 'ਆਪੁ ਆਪਨੀ ਬੂਝ ਉਚਾਰੈ ॥',
      pronunciation: 'āp āpanī būjh ucārē ‖',
      translation: 'speak about Him according to their understanding',
    },
    {
      id: 'R0LK',
      src: 'ਤੁਮ ਸਭ ਹੀ ਤੇ ਰਹਤ ਨਿਰਾਲਮ ॥',
      pronunciation: 'tum sabh hī te rahat nirālam ‖',
      translation: 'But Thou, O Lord! live quite apart from everything',
    },
    {
      id: '9AAW',
      src: 'ਜਾਨਤ ਬੇਦ ਭੇਦ ਅਰ ਆਲਮ ॥੩੯੦॥',
      pronunciation: 'jānat bed bhed ar ālam ‖390‖',
      translation: 'this fact is know to the Vedas and the learned.390.',
    },
    {
      id: '1MMU',
      src: 'ਨਿਰੰਕਾਰ ਨ੍ਰਿਬਿਕਾਰ ਨਿਰਲੰਭ ॥',
      pronunciation: 'nirañkār nribikār niralañbh ‖',
      translation: 'The Lord is Formless, Sinless and shelterless:',
    },
    {
      id: 'T1T4',
      src: 'ਆਦਿ ਅਨੀਲ ਅਨਾਦਿ ਅਸੰਭ ॥',
      pronunciation: 'ād anīl anād asañbh ‖',
      translation:
        'He is the Primal Power, without Blemish, without Beginning and Unborn',
    },
    {
      id: 'YN4A',
      src: 'ਤਾ ਕਾ ਮੂੜ੍ਹ ਉਚਾਰਤ ਭੇਦਾ ॥',
      pronunciation: 'tā kā mūṛh ucārat bhedā ‖',
      translation:
        'The fool claims boastfully about the knowledge of His secrets,',
    },
    {
      id: 'AVLG',
      src: 'ਜਾ ਕੋ ਭੇਵ ਨ ਪਾਵਤ ਬੇਦਾ ॥੩੯੧॥',
      pronunciation: 'jā ko bhev na pāwat bedā ‖391‖',
      translation: 'which even the Vedas do not know.391.',
    },
    {
      id: '6VZ6',
      src: 'ਤਾ ਕੋ ਕਰਿ ਪਾਹਨ ਅਨੁਮਾਨਤ ॥',
      pronunciation: 'tā ko kar pāhan anumānat ‖',
      translation: 'The fool considers Him a stone,',
    },
    {
      id: 'U5RH',
      src: 'ਮਹਾ ਮੂੜ੍ਹ ਕਛੁ ਭੇਦ ਨ ਜਾਨਤ ॥',
      pronunciation: 'mahā mūṛh kach bhed na jānat ‖',
      translation: 'but the great fool does not know any secret',
    },
    {
      id: 'LQH8',
      src: 'ਮਹਾਦੇਵ ਕੋ ਕਹਤ ਸਦਾ ਸਿਵ ॥',
      pronunciation: 'mahādev ko kahat sadā siv ‖',
      translation: 'He calls Shiva “The Eternal Lord,',
    },
    {
      id: 'EANN',
      src: 'ਨਿਰੰਕਾਰ ਕਾ ਚੀਨਤ ਨਹਿ ਭਿਵ ॥੩੯੨॥',
      pronunciation: 'nirañkār kā cīnat nah bhiv ‖392‖',
      translation: '“but he does not know the secret of the Formless Lord.392.',
    },
    {
      id: '9MQD',
      src: 'ਆਪੁ ਆਪਨੀ ਬੁਧਿ ਹੈ ਜੇਤੀ ॥',
      pronunciation: 'āp āpanī budh hē jetī ‖',
      translation: 'According to ones won intellect,',
    },
    {
      id: 'D9E9',
      src: 'ਬਰਨਤ ਭਿੰਨ ਭਿੰਨ ਤੁਹਿ ਤੇਤੀ ॥',
      pronunciation: 'baranat bhiñn bhiñn tuh tetī ‖',
      translation: 'one describes Thee differently',
    },
    {
      id: 'NG2W',
      src: 'ਤੁਮਰਾ ਲਖਾ ਨ ਜਾਇ ਪਸਾਰਾ ॥',
      pronunciation: 'tumarā lakhā na jāi pasārā ‖',
      translation: 'The limits of Thy creation cannot be known',
    },
    {
      id: '6FWW',
      src: 'ਕਿਹ ਬਿਧਿ ਸਜਾ ਪ੍ਰਥਮ ਸੰਸਾਰਾ ॥੩੯੩॥',
      pronunciation: 'kih bidh sajā pratham sañsārā ‖393‖',
      translation: 'and how the world was fashioned in the beginning?393.',
    },
    {
      id: 'HFDS',
      src: 'ਏਕੈ ਰੂਪ ਅਨੂਪ ਸਰੂਪਾ ॥',
      pronunciation: 'ekē rūp anūp sarūpā ‖',
      translation: 'He hath only one unparalleled Form',
    },
    {
      id: 'F3TU',
      src: 'ਰੰਕ ਭਯੋ ਰਾਵ ਕਹੀ ਭੂਪਾ ॥',
      pronunciation: 'rañk bhayo rāv kahī bhūpā ‖',
      translation:
        'He manifests Himself as a poor man or a king at different places',
    },
    {
      id: 'Q6WX',
      src: 'ਅੰਡਜ ਜੇਰਜ ਸੇਤਜ ਕੀਨੀ ॥',
      pronunciation: 'añḍaj jeraj setaj kīnī ‖',
      translation: 'He created creatures from eggs, wombs and perspiration',
    },
    {
      id: '1RMW',
      src: 'ਉਤਭੁਜ ਖਾਨਿ, ਬਹੁਰ ਰਚਿ ਦੀਨੀ ॥੩੯੪॥',
      pronunciation: 'utabhuj khāni, bahur rac dīnī ‖394‖',
      translation: 'Then He created the vegetable kingdom.394.',
    },
    {
      id: '7NL5',
      src: 'ਕਹੂੰ, ਫੂਲਿ ਰਾਜਾ ਹ੍ਵੈ ਬੈਠਾ ॥',
      pronunciation: 'kahūñ, phūl rājā hvē bēṭhā ‖',
      translation: 'Somewhere He sits joyfully as a king',
    },
    {
      id: 'FZV8',
      src: 'ਕਹੂੰ, ਸਿਮਟਿ ਭਿ︀ਯੋ ਸੰਕਰ ਇਕੈਠਾ ॥',
      pronunciation: 'kahūñ, simaṭ bhiyo sañkar ikēṭhā ‖',
      translation: 'Somewhere He contracts Himself as Shiva, the Yogi',
    },
    {
      id: 'BM8P',
      src: 'ਸਗਰੀ ਸ੍ਰਿਸਟਿ ਦਿਖਾਇ ਅਚੰਭਵ ॥',
      pronunciation: 'sagarī srisaṭ dikhāi acañbhav ‖',
      translation: 'All His creation unfolds wonderful things',
    },
    {
      id: 'JF4B',
      src: 'ਆਦਿ ਜੁਗਾਦਿ ਸਰੂਪ ਸੁਯੰਭਵ ॥੩੯੫॥',
      pronunciation: 'ād jugād sarūp suyañbhav ‖395‖',
      translation:
        'He, the Primal Power, is from the beginning and Self-Existent.395.',
    },
    {
      id: '71QS',
      src: 'ਅਬ, ਰੱਛਾ ਮੇਰੀ ਤੁਮ ਕਰੋ ॥',
      pronunciation: 'ab, racchā merī tum karo ‖',
      translation: 'O Lord! keep me now under Thy protection',
    },
    {
      id: '805N',
      src: 'ਸਿੱਖ ਉਬਾਰਿ ਅਸਿੱਖ ਸੰਘਰੋ ॥',
      pronunciation: 'sikkh ubār asikkh sañgharo ‖',
      translation: 'Protect my disciples and destroy my enemies',
    },
    {
      id: 'SY2L',
      src: 'ਦੁਸ਼ਟ ਜਿਤੇ ਉਠਵਤ ਉਤਪਾਤਾ ॥',
      pronunciation: 'dushaṭ jite uṭhawat utapātā ‖',
      translation: '',
    },
    {
      id: 'QUZX',
      src: 'ਸਕਲ ਮਲੇਛ, ਕਰੋ ਰਣ ਘਾਤਾ ॥੩੯੬॥',
      pronunciation: 'sakal malech, karo raṇ ghātā ‖396‖',
      translation:
        'All the villains creations outrage and all the infidels be destroyed in the battlefield.396.',
    },
    {
      id: 'YHUZ',
      src: 'ਜੇ ਅਸਿਧੁਜ, ਤਵ ਸਰਨੀ ਪਰੇ ॥',
      pronunciation: 'je asidhuj, tav saranī pare ‖',
      translation: '',
    },
    {
      id: 'MZKC',
      src: 'ਤਿਨ ਕੇ ਦੁਸਟ, ਦੁਖਿਤ ਹ੍ਵੈ ਮਰੇ ॥',
      pronunciation: 'tin ke dusaṭ, dukhit hvē mare ‖',
      translation:
        'O Supreme Destroyer! those who sought Thy refuge, their enemies met painful death',
    },
    {
      id: 'HQT7',
      src: 'ਪੁਰਖ ਜਵਨ, ਪਗ ਪਰੇ ਤਿਹਾਰੇ ॥',
      pronunciation: 'purakh jawan, pag pare tihāre ‖',
      translation: '',
    },
    {
      id: 'DG71',
      src: 'ਤਿਨ ਕੇ, ਤੁਮ ਸੰਕਟ ਸਭ ਟਾਰੇ ॥੩੯੭॥',
      pronunciation: 'tin ke, tum sañkaṭ sabh ṭāre ‖397‖',
      translation:
        'The persons who fell at Thy Feet, Thou didst remove all their troubles.397.',
    },
    {
      id: '60B3',
      src: 'ਜੋ ਕਲਿ ਕੋ, ਇਕ ਬਾਰ ਧਿਐਹੈ ॥',
      pronunciation: 'jo kal ko, ik bār dhiēhē ‖',
      translation: '',
    },
    {
      id: 'WYU8',
      src: 'ਤਾ ਕੇ, ਕਾਲ ਨਿਕਟਿ ਨਹਿ ਐਹੈ ॥',
      pronunciation: 'tā ke, kāl nikaṭ nah ēhē ‖',
      translation:
        'Those who meditate even on the Supreme Destroyer, the death cannot approach them',
    },
    {
      id: 'A77Y',
      src: 'ਰੱਛਾ ਹੋਇ ਤਾਹਿ, ਸਭ ਕਾਲਾ ॥',
      pronunciation: 'racchā hoi tāhi, sabh kālā ‖',
      translation: 'They remain protected at all times',
    },
    {
      id: 'XM2F',
      src: 'ਦੁਸਟ ਅਰਿਸਟ ਟਰੇਂ ਤਤਕਾਲਾ ॥੩੯੮॥',
      pronunciation: 'dusaṭ arisaṭ ṭareñ tatakālā ‖398‖',
      translation: 'Their enemies and troubles come to and end instantly.398.',
    },
    {
      id: 'BDK7',
      src: 'ਕ੍ਰਿਪਾ ਦ੍ਰਿਸਟਿ, ਤਨ ਜਾਹਿ ਨਿਹਰਿਹੋ ॥',
      pronunciation: 'kripā drisaṭi, tan jāh nihariho ‖',
      translation: '',
    },
    {
      id: 'GUWQ',
      src: 'ਤਾ ਕੇ ਤਾਪ, ਤਨਕ ਮੋ ਹਰਿਹੋ ॥',
      pronunciation: 'tā ke tāp, tanak mo hariho ‖',
      translation:
        'Upon whomsoever Thou dost cast Thy favourable glance, they are absolved of sins instantly',
    },
    {
      id: '0910',
      src: 'ਰਿੱਧਿ ਸਿੱਧਿ, ਘਰ ਮੋ ਸਭ ਹੋਈ ॥',
      pronunciation: 'riddh siddhi, ghar mo sabh hoī ‖',
      translation:
        'They have all the worldly and spiritual pleasures in their homes',
    },
    {
      id: 'QY45',
      src: 'ਦੁਸ਼ਟ ਛਾਹ, ਛ੍ਵੈ ਸਕੈ ਨ ਕੋਈ ॥੩੯੯॥',
      pronunciation: 'dushaṭ chāh, chvē sakē na koī ‖399‖',
      translation: 'None of th enemies can even touch their shadow.399.',
    },
    {
      id: 'BR5R',
      src: 'ਏਕ ਬਾਰ, ਜਿਨ ਤੁਮੈ ਸੰਭਾਰਾ ॥',
      pronunciation: 'ek bār, jin tumē sañbhārā ‖',
      translation: '',
    },
    {
      id: '6SU7',
      src: 'ਕਾਲ ਫਾਸ ਤੇ, ਤਾਹਿ ਉਬਾਰਾ ॥',
      pronunciation: 'kāl phās te, tāh ubārā ‖',
      translation:
        'He, who remembered Thee even once, Thou didst protect him from the noose of death',
    },
    {
      id: 'U5NC',
      src: 'ਜਿਨ ਨਰ, ਨਾਮ ਤਿਹਾਰੋ ਕਹਾ ॥',
      pronunciation: 'jin nar, nām tihāro kahā ‖',
      translation: '',
    },
    {
      id: 'XWRL',
      src: 'ਦਾਰਿਦ ਦੁਸਟ ਦੋਖ ਤੇ ਰਹਾ ॥੪੦੦॥',
      pronunciation: 'dārid dusaṭ dokh te rahā ‖400‖',
      translation:
        'Those persons, who repeated Thy Name, they were saved from poverty and attacks of enemies.400.',
    },
    {
      id: 'M5M5',
      src: 'ਖੜਗ ਕੇਤ, ਮੈ ਸਰਣਿ ਤਿਹਾਰੀ ॥',
      pronunciation: 'khaṛag ket, mē saraṇ tihārī ‖',
      translation: '',
    },
    {
      id: 'QP2A',
      src: 'ਆਪ, ਹਾਥ ਦੈ ਲੇਹੁ ਉਬਾਰੀ ॥',
      pronunciation: 'āp, hāth dē leh ubārī ‖',
      translation:
        'Bestow thy help own me at all places protect me from the design of my enemies. 401.',
    },
    {
      id: 'LYXN',
      src: 'ਸਰਬ ਠੌਰ, ਮੋ ਹੋਹੁ ਸਹਾਈ ॥',
      pronunciation: 'sarab ṭhōr, mo hoh sahāī ‖',
      translation: '',
    },
    {
      id: 'DM0Z',
      src: 'ਦੁਸਟ ਦੋਖ ਤੇ, ਲੇਹੁ ਬਚਾਈ ॥੪੦੧॥',
      pronunciation: 'dusaṭ dokh te, leh bacāī ‖401‖',
      translation:
        'Bestow Thy help on me at all places and protect me from the designs of my enemies.401.',
    },
  ],
};

export const onGet: RequestHandler = async ({ json }) => {
  json(200, data);
};
